# Generated by Django 2.0.4 on 2018-05-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_class', models.CharField(max_length=50)),
                ('field_name', models.SlugField(max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genschema.Schema')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genschema.Schema')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaIValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldvalue', models.TextField()),
                ('schemafield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genschema.SchemaField')),
                ('schemainstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genschema.SchemaInstance')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schemaivalue',
            unique_together={('schemainstance', 'schemafield')},
        ),
        migrations.AlterUniqueTogether(
            name='schemafield',
            unique_together={('schema', 'field_name')},
        ),
    ]
