# Generated by Django 2.0.4 on 2018-05-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genschema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemaivalue',
            options={'ordering': ('schemainstance', 'schemafield')},
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='genschema.Schema'),
        ),
    ]
